{pkgs}: {
  deps = [
    pkgs.netcat
    pkgs.rPackages.mosum
    pkgs.rPackages.Mu15v1_db
    pkgs.rubyPackages_3_2.activejob
    pkgs.python310Packages.webthing
    pkgs.haskellPackages.data-r-tree
    pkgs.perlPackages.iCalParser
    pkgs.sbclPackages.coleslaw
    pkgs.wordpress6_4
    pkgs.rPackages.ympes
    pkgs.rPackages.scorecardModelUtils
    pkgs.gnomeExtensions.kimpanel
    pkgs.purenix
    pkgs.libsForQt5.qtwebkit
    pkgs.rubyPackages_3_2.rack-test
    pkgs.sbclPackages.cl-memcached
    pkgs.libsForQt5.kblocks
    pkgs.rPackages.opendotaR
    pkgs.sbclPackages.qvm-examples
    pkgs.vcmi
    pkgs.haskellPackages.haskell-dap
    pkgs.haskellPackages.solve
    pkgs.rPackages.frailtyEM
    pkgs.vimPlugins.neotest
    pkgs.vimPlugins.vim-svelte
    pkgs.rPackages.mda
    pkgs.vimPlugins.vim-visual-multi
    pkgs.python311Packages.pylibmc
    pkgs.perlPackages.Testmysqld
    pkgs.python311Packages.stestr
    pkgs.rPackages.neatR
    pkgs.deepin.dwayland
    pkgs.miniball
    pkgs.emacsPackages.flycheck-clangcheck
    pkgs.emacsPackages.solo-jazz-theme
    pkgs.libcardiacarrest
    pkgs.gnomeExtensions.net-speed
    pkgs.rPackages.apportion
    pkgs.python311Packages.aionanoleaf
    pkgs.haskellPackages.dependent-map_0_2_4_0
    pkgs.python311Packages.pixel-ring
    pkgs.rPackages.motifbreakR
    pkgs.rubyPackages_3_2.forwardable-extended
    pkgs.ppsspp-qt
    pkgs.gnomeExtensions.window-calls-extended
    pkgs.ipscan
    pkgs.haskellPackages.phonetic-languages-phonetics-basics
    pkgs.sbclPackages.cl-glfw-opengl-sgis__texture__filter4
    pkgs.python312Packages.nvdlib
    pkgs.lua51Packages.luatext
    pkgs.leiningen
    pkgs.bsequencer
    pkgs.sbclPackages.lispqr
    pkgs.haskellPackages.optimusprime
    pkgs.gnomeExtensions.eortologio-extension
    pkgs.lomiri.lomiri-wallpapers
    pkgs.cudaPackages.cuda_nvprof
    pkgs.rPackages.DIME
    pkgs.rPackages.AllPossibleSpellings
    pkgs.chromium
    pkgs.postgresql
    pkgs.jq
  ];
}
